#!/bin/sh


#PBS -N pcp_
#PBS -l walltime=00:35:00
#PBS -q mei

#PBS -m abe
#PBS -M carlos.sa01@gmail.com
#PBS -M a69855@alunos.uminho.pt


#PBS -l nodes=2:r641:ppn=32

cd PCP_-_#2_MPI_Sparse_Matrix/ 
module purge
module load gnu/4.9.0
module load gnu/4.9.3
module load gnu/openmpi_eth/1.8.4
ompi_info --param mpi all
read -r node_info<$PBS_NODEFILE

echo "Allocated computing node: $node_info"

max_ppn=32
sample_size=8
max_matrix=4096

for (( matrix_size=1024;matrix_size <= $max_matrix; matrix_size+=matrix_size  ))
	do 
	for (( ppn = 1; ppn <= max_ppn; ++ppn )) 
		do
		echo "Running $sample_size * ppn: $ppn nodes"
		for (( seq_num=1; seq_num <= $sample_size; ++seq_num ))
			do
			mpirun -np $ppn --map-by core -mca btl self,sm,tcp --report-bindings bin/pcp_tp2_mpi $matrix_size "--map-by core ETH" 
		done
	done
done

mv pcp_tp2_mpi_* results/
echo "Done..."
